# - Comment

# we can have yaml files with .yml or .yaml as extension

# Key Values

# Set Of Key Values (Map/Dictionary)

# Multiple Items (List/Array)

# Simple Key Values Representation
key: value
name: ravi
city: hyderabad
zip: 500081

# Set Of Key Values (Map/Dictionary) Representation
trainer:
  name: ravi
  city: hyderabad
  zip: 500081

student:
  name: ram
  course: devops
  class_mode: online

# Mutiple Items (List/Array) Representation  
courses:
- aws
- azure
- devops
- python